name: Mozcloud Demo -- Build and Push Container Image to GAR

on:
  push:
    branches:
      - main
    tags:
      - v20[0-9][0-9].[01][0-9].[0-3][0-9]  # e.g. v2023.12.04
      - v20[0-9][0-9].[01][0-9].[0-3][0-9]-[0-9]  # e.g. v2023.12.04-2
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: mzcld-demo-web
  LOAD_TESTS_IMAGE_NAME: mzcld-demo-load-tests
  GCP_PROJECT_ID: moz-fx-mzcld-demo-prod
  IMAGE_REPO_PATH: moz-fx-mzcld-demo-prod/mzcld-demo-prod/mzcld-demo
  LOAD_TESTS_IMAGE_REPO_PATH: moz-fx-mzcld-demo-prod/mzcld-demo-prod/mzcld-demo-load-tests

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - name: Run the release script to build version.json file
        working-directory: .
        run: ./script/update_version.sh
      - name: Output version.json
        run: cat version.json
      - name: Build Docker image
        run: make build
      - name: Build load-test Docker image
        run: |
          docker build -t mzcld-demo-load-tests:latest ./load-tests/
      - name: Run tests in Docker image
        run: make test
      - name: Set Docker image tag to sha for updates of the main branch
        if: github.ref == 'refs/heads/main'
        run: |
          echo IMAGE_TAG=$(git rev-parse --short=10 "$GITHUB_SHA") >> "$GITHUB_ENV"
      - name: Set Docker image tag to the git tag for tagged builds
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo IMAGE_TAG="$GITHUB_REF_NAME" >> "$GITHUB_ENV"
      - name: Push Docker image to GAR
        if: env.IMAGE_TAG != ''
        uses: mozilla-it/deploy-actions/docker-push@v3.11.1
        with:
          local_image: ${{ env.IMAGE_NAME }}
          image_repo_path: ${{ env.IMAGE_REPO_PATH }}
          image_tag: ${{ env.IMAGE_TAG }}
          workload_identity_pool_project_number: ${{ vars.GCPV2_WORKLOAD_IDENTITY_POOL_PROJECT_NUMBER }}
          project_id: ${{ env.GCP_PROJECT_ID }}
      - name: Push load-test Docker image to GAR
        if: env.IMAGE_TAG != ''
        uses: mozilla-it/deploy-actions/docker-push@v3.11.1
        with:
          local_image: ${{ env.LOAD_TESTS_IMAGE_NAME }}
          image_repo_path: ${{ env.LOAD_TESTS_IMAGE_REPO_PATH }}
          image_tag: latest
          workload_identity_pool_project_number: ${{ vars.GCPV2_WORKLOAD_IDENTITY_POOL_PROJECT_NUMBER }}
          project_id: ${{ env.GCP_PROJECT_ID }}
